# Generated by Django 4.0.5 on 2022-07-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='donation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donations',
            name='venue',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='donations',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
