# Generated by Django 4.0.6 on 2022-07-07 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0003_alter_donations_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='name',
            new_name='donorname',
        ),
        migrations.RemoveField(
            model_name='donations',
            name='donation_date',
        ),
        migrations.RemoveField(
            model_name='donations',
            name='venue',
        ),
        migrations.AddField(
            model_name='donations',
            name='donationdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donations',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation', to=settings.AUTH_USER_MODEL),
        ),
    ]
