# Generated by Django 4.0.6 on 2022-07-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donations_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='donation_date',
            new_name='donationdate',
        ),
    ]
