# Generated by Django 4.0.6 on 2022-07-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_rename_donation_date_donations_donationdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='name',
            new_name='donorname',
        ),
        migrations.RemoveField(
            model_name='donations',
            name='venue',
        ),
        migrations.AlterField(
            model_name='donations',
            name='donationdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
