# Generated by Django 4.0.5 on 2022-07-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('approximate_sallary', models.PositiveIntegerField(default=0)),
                ('deadline', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
