# Generated by Django 4.0.6 on 2022-07-04 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Gene', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
