# Generated by Django 4.0.6 on 2022-07-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gene', '0002_employer_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='category',
        ),
    ]
