# Generated by Django 4.0.6 on 2022-07-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gene', '0003_remove_employer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='category',
            field=models.CharField(default='exit', max_length=40),
            preserve_default=False,
        ),
    ]
