# Generated by Django 4.0.6 on 2022-07-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gene', '0004_employer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='category',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
