# Generated by Django 4.0.6 on 2022-07-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gene', '0005_rename_approximate_sallary_employer_approximate_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='deadline',
            field=models.DateField(auto_now=True),
        ),
    ]
