# Generated by Django 4.0.6 on 2022-07-06 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gene', '0006_employer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='approximate_sallary',
            new_name='approximate_salary',
        ),
    ]
