# Generated by Django 4.0.5 on 2022-07-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0003_alter_projectpitch_decription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpitch',
            name='decription',
            field=models.TextField(max_length=200),
        ),
    ]
