# Generated by Django 4.0.5 on 2022-07-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0004_alter_projectpitch_decription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpitch',
            name='total_cost',
            field=models.IntegerField(),
        ),
    ]
