# Generated by Django 4.0.5 on 2022-07-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0005_alter_projectpitch_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpitch',
            old_name='decription',
            new_name='description',
        ),
    ]
