# Generated by Django 4.0.5 on 2022-07-04 05:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('eventdate', models.DateTimeField()),
            ],
        ),
    ]
