# Generated by Django 4.0.5 on 2022-07-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='training',
            name='venue',
            field=models.CharField(max_length=200),
        ),
    ]
