# Generated by Django 4.0.6 on 2022-07-07 21:35

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Training', '0002_alter_training_category_alter_training_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='eventtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='training',
            name='eventdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='poster',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
