# Generated by Django 4.0.6 on 2022-07-05 19:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0003_training_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='poster',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
