# Generated by Django 4.0.6 on 2022-07-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0005_alter_training_eventdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='eventdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
